import type { DocumentExtractionPolicy, DocumentPage, ExtractionCandidate } from "../lib/document-intelligence.ts";

export const documentIntelligenceLab = {
  path: "/labs/inteligencia-documental",
  title: "Document Intelligence Lab: extracción, evidencia y revisión",
  description: "Prueba reproducible de extracción documental con página y fragmento exactos, contradicciones, confianza y revisión humana según el riesgo del campo.",
  updatedAt: "2026-09-13",
  lead: "Extraer un valor no basta. Esta prueba obliga a comprobar de dónde sale, si el documento lo contradice y cuándo el riesgo exige que una persona decida.",
  scope: "Contrato y extracciones completamente sintéticos, preparados por Ordantis para explicar el método. No se suben archivos, no se ejecuta OCR, no se llama a un modelo y no se tratan datos de clientes. Los porcentajes de confianza son valores de prueba, no rendimiento medido.",
  method: [
    "Cada candidato declara campo, valor, página, fragmento literal, confianza y riesgo. La página y el fragmento deben poder comprobarse contra el contrato mostrado.",
    "La evaluación normaliza mayúsculas, acentos y espacios, pero exige que el fragmento exista en la página indicada. Una página inexistente o un fragmento inventado invalidan la cita.",
    "La política se aplica en orden: evidencia ausente o inválida, contradicción, riesgo alto y umbral de confianza. La primera regla aplicable determina aceptar, revisar o rechazar.",
    "Aceptar significa que este conjunto preparado no activa una revisión. No autoriza a escribir el dato en otro sistema ni sustituye controles del proceso.",
    "La decisión se compara con una expectativa declarada. Una aceptación insegura es un candidato aceptado cuando la expectativa exigía revisar o rechazar.",
  ],
  limitations: [
    "El contrato, los candidatos y las expectativas son didácticos. No proceden de expedientes, contratos ni resultados de clientes.",
    "No se mide OCR, tablas, firmas, sellos, anexos, versiones, documentos escaneados ni resistencia a instrucciones maliciosas incluidas en un archivo.",
    "La confianza está preparada para esta demostración. En un sistema real debe calibrarse con un conjunto separado y revisarse por tipo de documento y campo.",
    "Una coincidencia textual no demuestra que la interpretación jurídica sea correcta. Fechas, importes, obligaciones y excepciones necesitan reglas de negocio y revisión competente.",
    "Diez aciertos solo demuestran que esta función coincide con las expectativas publicadas. No constituyen un benchmark de modelos ni una certificación de inteligencia documental.",
  ],
  related: [
    { path: "/insights/rag-abstencion-evidencia", label: "RAG con abstención y evidencia" },
    { path: "/insights/informe-tecnico-sin-inventar-informacion", label: "Informes técnicos sin inventar información" },
    { path: "/insights/expediente-computable", label: "Expediente computable con fuentes y versiones" },
    { path: "/capacidades/document-intelligence", label: "Document Intelligence: alcance y entregables" },
  ],
} as const;

export const syntheticContractPages: DocumentPage[] = [
  {
    page: 1,
    text: "Contrato de servicios de demostración. Proveedor: Nébula Demo S.L. Inicio: 15/10/2026. Duración: 12 meses.",
  },
  {
    page: 2,
    text: "Importe anual máximo: 48.000 EUR, impuestos no incluidos. Responsable funcional: Operaciones y Logística.",
  },
  {
    page: 3,
    text: "La resolución anticipada requiere un preaviso mínimo de 60 días. No se establece renovación automática.",
  },
  {
    page: 4,
    text: "El tratamiento se realizará dentro del Espacio Económico Europeo. Los incidentes se comunicarán en un máximo de 24 horas.",
  },
];

export const defaultDocumentExtractionPolicy: DocumentExtractionPolicy = {
  minimumConfidence: 0.75,
  requireEvidence: true,
  reviewContradictions: true,
  reviewHighRisk: true,
};

export const extractionCandidates: ExtractionCandidate[] = [
  {
    id: "d01",
    field: "Proveedor",
    value: "Nébula Demo S.L.",
    page: 1,
    excerpt: "Proveedor: Nébula Demo S.L.",
    supportText: "Nébula Demo S.L.",
    confidence: 0.99,
    risk: "low",
    expectedDecision: "accept",
    expectedReason: "Valor literal, cita válida y riesgo bajo.",
  },
  {
    id: "d02",
    field: "Fecha de inicio",
    value: "15/10/2026",
    page: 1,
    excerpt: "Inicio: 15/10/2026.",
    supportText: "15/10/2026",
    confidence: 0.96,
    risk: "medium",
    expectedDecision: "accept",
    expectedReason: "La fecha aparece literalmente y supera el umbral.",
  },
  {
    id: "d03",
    field: "Duración",
    value: "12 meses",
    page: 1,
    excerpt: "Duración: 12 meses.",
    supportText: "12 meses",
    confidence: 0.92,
    risk: "medium",
    expectedDecision: "accept",
    expectedReason: "La duración está respaldada y no se clasificó como campo de alto riesgo.",
  },
  {
    id: "d04",
    field: "Importe anual máximo",
    value: "48.000 EUR",
    page: 2,
    excerpt: "Importe anual máximo: 48.000 EUR, impuestos no incluidos.",
    supportText: "48.000 EUR",
    confidence: 0.88,
    risk: "high",
    expectedDecision: "review",
    expectedReason: "El importe está respaldado, pero un campo económico requiere revisión humana.",
  },
  {
    id: "d05",
    field: "Preaviso",
    value: "30 días",
    page: 3,
    excerpt: "La resolución anticipada requiere un preaviso mínimo de 60 días.",
    supportText: "30 días",
    conflictingText: "60 días",
    confidence: 0.92,
    risk: "high",
    expectedDecision: "review",
    expectedReason: "La cita contradice el valor extraído: muestra 60 días, no 30.",
  },
  {
    id: "d06",
    field: "Renovación automática",
    value: "Sí",
    page: 3,
    excerpt: "No se establece renovación automática.",
    supportText: "Sí",
    conflictingText: "No se establece renovación automática",
    confidence: 0.84,
    risk: "high",
    expectedDecision: "review",
    expectedReason: "La extracción afirma lo contrario de la cláusula citada.",
  },
  {
    id: "d07",
    field: "Penalización por demora",
    value: "5 %",
    page: null,
    excerpt: null,
    supportText: "5 %",
    confidence: 0.77,
    risk: "high",
    expectedDecision: "reject",
    expectedReason: "El contrato mostrado no aporta página ni fragmento que respalden esa penalización.",
  },
  {
    id: "d08",
    field: "Ubicación del tratamiento",
    value: "Espacio Económico Europeo",
    page: 4,
    excerpt: "El tratamiento se realizará dentro del Espacio Económico Europeo.",
    supportText: "Espacio Económico Europeo",
    confidence: 0.91,
    risk: "high",
    expectedDecision: "review",
    expectedReason: "La localización está respaldada, pero afecta a una condición de tratamiento de datos.",
  },
  {
    id: "d09",
    field: "Notificación de incidentes",
    value: "24 horas",
    page: 4,
    excerpt: "Los incidentes se comunicarán en un máximo de 24 horas.",
    supportText: "24 horas",
    confidence: 0.79,
    risk: "high",
    expectedDecision: "review",
    expectedReason: "El plazo se cita correctamente, pero activa revisión por riesgo alto.",
  },
  {
    id: "d10",
    field: "Responsable funcional",
    value: "Operaciones y Logística",
    page: 2,
    excerpt: "Responsable funcional: Operaciones y Logística.",
    supportText: "Operaciones y Logística",
    confidence: 0.70,
    risk: "medium",
    expectedDecision: "review",
    expectedReason: "La cita es válida, pero la confianza queda por debajo del umbral inicial.",
  },
];
